# Generated by Django 4.2.10 on 2024-02-08 03:53

from django.db import migrations, models
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('car_number', models.CharField(max_length=25)),
                ('parking_status', models.PositiveSmallIntegerField(choices=[(1, 'Entry'), (2, 'Exit'), (3, 'Queue')])),
                ('entry_date', models.DateTimeField(blank=True, default=None, null=True)),
                ('exit_date', models.DateTimeField(blank=True, default=None, null=True)),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
            },
        ),
    ]
